### ISSUE TITLE
 undefined method `to_date'

### ISSUE THREAD

**Issue by krishamehta** [poole/hyde#215]
When I try to run my server, I get the following error:

`Liquid Exception: undefined method `to_date' for Liquid::Utils:Module in /_layouts/post.html
jekyll 3.6.2 | Error:  undefined method `to_date' for Liquid::Utils:Module
`

**Comment by kssim** [comment]
Your problem(@krishamehta) seems to be a problem with the installed liquid version of your system. It seems to be a problem because the version of liquid installed on the system is less than 4.0.0. Remove the liquid installed on your system and reinstall liquid with <code>gem install</code>.

If you are using Debian Linux, do the following:
<code>sudo apt-get remove ruby-liquid</code>
<code>sudo gem install liquid</code>

**Comment by mtbc** [comment]
Can also just pull in the `ruby-liquid` from testing/buster.
