### ISSUE TITLE
No page style

### ISSUE THREAD

**Issue by hugginsio** [poole/hyde#54]
Direct fork, with only one change: I deleted the CNAME file. Still, no styling appears when I goto the site. [Here](//epiquiem.github.io/hyde) is the site, [here](//github.com/epiquiem/hyde) is the repo. Thanks for your help!

**Comment by dmcglinn** [comment]
I am experiencing the same problem and modifying the `baseurl` to `\hyde` or `\hyde\` did not solve the problem. Additionally this problem seems strange because the local version of the site looks good as generated with `jekyll serve`, it is just appears to be a problem with how github is serving the site where the problem with the site style arises. Here is the git repo: https://github.com/dmcglinn/quant_methods and here is the site page: http://dmcglinn.github.io/quant_methods/

**Comment by nicolasmccurdy** [comment]
@epiquiem Do you still need help with your issues?

@dmcglinn It seems like you're either missing a `/` or adding an extra `\` in your URLs. Here's what I'm seeing when I visit your site:
```
GET http://dmcglinn.github.io/hydepublic/css/poole.css [HTTP/1.1 404 Not Found 38ms]
GET http://dmcglinn.github.io/hydepublic/css/syntax.css [HTTP/1.1 404 Not Found 37ms]
GET http://dmcglinn.github.io/hydepublic/css/hyde.css [HTTP/1.1 404 Not Found 38ms]
```

**Comment by dmcglinn** [comment]
thanks @nicolasmccurdy but actually the solution was what @mdo had suggested I was just misinterpreting his suggestion. When I changed the `baseurl` to match my site (i.e., /quant_methods/) it worked great!

**Comment by bazbt3** [comment]
And here we are, 2-3 years later, with me using this issue to fix a failing page after, I’d presume, a GitHub Pages system update. Thanks all!
